### ISSUE TITLE
配合路由使用，切换路径的时候会报错

### ISSUE THREAD

**Issue by LiHaoGit** [vortesnail/qier-player#10]
复现 https://codesandbox.io/s/gracious-minsky-vti1u

当跳转到其他的url的时候，会报错

**Comment by vortesnail** [comment]
> 复现 https://codesandbox.io/s/gracious-minsky-vti1u
> 
> 当跳转到其他的url的时候，会报错

晚上下班之后我看看，肯定是清除监听那块儿我没写好，小问题哈。

**Comment by LiHaoGit** [comment]
我提pr了

**Comment by vortesnail** [comment]
已合并～
