### ISSUE TITLE
试一下这个

### ISSUE THREAD

**Issue by LiHaoGit** [vortesnail/qier-player#12]
https://github.com/vortesnail/qier-player/blob/e2bdcb46bc04beb6098d65023e013b6237be38ef/src/component/controls/index.js#L223-#L236

```
  handleChangePlayState() {
    if (this.state.isPlay) {
      this.props.videoRef.current.pause();
      this.setState({ isPlay: false });
      // 这条 return 语句必须的加，不然下面的代码也会执行。。
      // 黑科技。。
      // 不是说 setState 是异步吗？？？
      return;
    }
    if (!this.state.isPlay) {
      this.props.videoRef.current.play();
      this.setState({ isPlay: true });
    }
  }
```

你看看
```
 handleChangePlayState() {
    if (this.state.isPlay) {
      this.props.videoRef.current.pause();
      this.setState({ isPlay: false });
      // 这条 return 语句必须的加，不然下面的代码也会执行。。
      // 黑科技。。
      // 不是说 setState 是异步吗？？？     
    } else {
      this.props.videoRef.current.play();
      this.setState({ isPlay: true });
    }
  }
```

或者
```
 handleChangePlayState() {
    this.setState(preState => {
      if (preState.isPlay) {
        this.props.videoRef.current.pause();
      } else {
        this.props.videoRef.current.play();
      }
      return { isPlay: !preState.isPlay };
    });
  }
```

**Comment by vortesnail** [comment]
> https://github.com/vortesnail/qier-player/blob/e2bdcb46bc04beb6098d65023e013b6237be38ef/src/component/controls/index.js#L223-#L236
> 
> ```
>   handleChangePlayState() {
>     if (this.state.isPlay) {
>       this.props.videoRef.current.pause();
>       this.setState({ isPlay: false });
>       // 这条 return 语句必须的加，不然下面的代码也会执行。。
>       // 黑科技。。
>       // 不是说 setState 是异步吗？？？
>       return;
>     }
>     if (!this.state.isPlay) {
>       this.props.videoRef.current.play();
>       this.setState({ isPlay: true });
>     }
>   }
> ```
> 
> 你看看
> 
> ```
>  handleChangePlayState() {
>     if (this.state.isPlay) {
>       this.props.videoRef.current.pause();
>       this.setState({ isPlay: false });
>       // 这条 return 语句必须的加，不然下面的代码也会执行。。
>       // 黑科技。。
>       // 不是说 setState 是异步吗？？？     
>     } else {
>       this.props.videoRef.current.play();
>       this.setState({ isPlay: true });
>     }
>   }
> ```
> 
> 或者
> 
> ```
>  handleChangePlayState() {
>     this.setState(preState => {
>       if (preState.isPlay) {
>         this.props.videoRef.current.pause();
>       } else {
>         this.props.videoRef.current.play();
>       }
>       return { isPlay: !preState.isPlay };
>     });
>   }
> ```

哈哈，说起来这个项目还是我刚学完react之后写的了，现在看看之前写的代码还真是一言难尽。。。感谢提出，我回去之后改下。。

btw，这个项目的代码的确看起来蛮乱的，有机会想用ts 和  hooks 重构一份。

事实上很多定时器都是没必要的。。

**Comment by LiHaoGit** [comment]
ok 你看下  [pr#11](https://github.com/vortesnail/qier-player/pull/11) 有没有问题，可以先发布一个

**Comment by vortesnail** [comment]
已调整
