### ISSUE TITLE
Unable to change src

### ISSUE THREAD

**Issue by lavanphat** [vortesnail/qier-player#14]
I use src as a state. When I change the state, do not reload the video. Now, what must I do. Thank you
![image](https://user-images.githubusercontent.com/45566810/80587451-ca03ad00-8a40-11ea-9c8b-94bde55be9c6.png)

**Comment by vortesnail** [comment]
> I use src as a state. When I change the state, do not reload the video. Now, what must I do. Thank you
> ![image](https://user-images.githubusercontent.com/45566810/80587451-ca03ad00-8a40-11ea-9c8b-94bde55be9c6.png)

hi,i have tried to make this bug happen, thanks for you feedback, i will fix it as soon as possible.

**Comment by vortesnail** [comment]
Now the problem had fixed, you can try  `npm install qier-player@1.2.10` and test it.
