### ISSUE TITLE
Control buttons visibility options

### ISSUE THREAD

**Issue by saurav90** [vortesnail/qier-player#17]
Can we have option to remove or add the control buttons individually, for example, I don't want the Play rate option. so can I be able to remove it?

I hope this will indeed a great feature to have the options customized.

**Comment by yash-me** [comment]
> Can we have option to remove or add the control buttons individually, for example, I don't want the Play rate option. so can I be able to remove it?
> 
> I hope this will indeed a great feature to have the options customized.

Hello Saurav, are you able to do so, as I want to remove the full-screen feature in API
