### ISSUE TITLE
是否可以支持直播流

### ISSUE THREAD

**Issue by d1y** [vortesnail/qier-player#2]
比如 `.flv` 或者 `rtmp://`. Thank you😊

**Comment by vortesnail** [comment]
> 比如 `.flv` 或者 `rtmp://`. Thank you😊

这个目前还没有支持，直播流需要后端支持，不好意思哈

**Comment by d1y** [comment]
> > 比如 `.flv` 或者 `rtmp://`. Thank you😊
> 
> 这个目前还没有支持，直播流需要后端支持，不好意思哈

B站开源的这个 `flv.js` ︿(￣︶￣)︿, 老哥看一下, 看看可不可以整到播放器里面
https://github.com/bilibili/flv.js

**Comment by vortesnail** [comment]
> > > 比如 `.flv` 或者 `rtmp://`. Thank you😊
> > 
> > 
> > 这个目前还没有支持，直播流需要后端支持，不好意思哈
> 
> B站开源的这个 `flv.js` ︿(￣︶￣)︿, 老哥看一下, 看看可不可以整到播放器里面
> https://github.com/bilibili/flv.js

欢迎作为贡献者贡献你的代码噢，最近工作太忙了！～

**Comment by d1y** [comment]
> > > > 比如 `.flv` 或者 `rtmp://`. Thank you😊
> > > 
> > > 
> > > 这个目前还没有支持，直播流需要后端支持，不好意思哈
> > 
> > 
> > B站开源的这个 `flv.js` ︿(￣︶￣)︿, 老哥看一下, 看看可不可以整到播放器里面
> > https://github.com/bilibili/flv.js
> 
> 欢迎作为贡献者贡献你的代码噢，最近工作太忙了！～

wowo, 白嫖习惯了, 贡献是不可能贡献的啦, 这辈几都不可能的啦~
