### ISSUE TITLE
替换官网使用文档中例子的视频链接，出现以下错误

### ISSUE THREAD

**Issue by QingYuanO** [vortesnail/qier-player#26]
![image](https://user-images.githubusercontent.com/42159029/147214073-5ee0acd9-1a0c-428d-b76c-ec46aba2789a.png)

**Comment by vortesnail** [comment]
> 

跨域了

**Comment by vortesnail** [comment]
> ![image](https://user-images.githubusercontent.com/42159029/147214073-5ee0acd9-1a0c-428d-b76c-ec46aba2789a.png)

你的地址贴一下，我看看
