### ISSUE TITLE
官方示例疑似BUG？

### ISSUE THREAD

**Issue by FontEndArt** [vortesnail/qier-player#8]
![image](https://user-images.githubusercontent.com/19547121/72693037-1732d180-3b6a-11ea-8c78-812a6d628321.png)
疑似bug：这个地方点击无效？

**Comment by FontEndArt** [comment]
考虑到国内可能看不了图片   文字说明：暂停状态下的窗口右下角的播放按钮点击无效

**Comment by vortesnail** [comment]
> 考虑到国内可能看不了图片 文字说明：暂停状态下的窗口右下角的播放按钮点击无效

收到，的确有这个情况，我修复一下

**Comment by vortesnail** [comment]
> 考虑到国内可能看不了图片 文字说明：暂停状态下的窗口右下角的播放按钮点击无效

已经修复，官网和npm包都已经修复。

**Comment by FontEndArt** [comment]
好的
